version: '3.8'

services:
  surrealdb:
    platform: 'linux/amd64'
    image: 'surrealdb/surrealdb:latest'
    command: start --user rgtg_admin --pass bWFubnk6c0FzMyp6MnAh rocksdb:/surrealdb/mydatabase.db
    ports:
      - '8000:8000'
    volumes:
      - ./surrealdb:/surrealdb
    networks:
      - backend
    restart: unless-stopped


  redis:
    image: redis:7.2.4-alpine
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5


  next-app:
    container_name: next-app
    image: mannyj37/rs-demo:latest
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://app.rightstudio.media}
        - NEXT_PUBLIC_DOCS_URL=${NEXT_PUBLIC_DOCS_URL:-https://docs.rightstudio.media}
        - NEXTAUTH_URL=${NEXTAUTH_URL:-https://app.rightstudio.media/api/auth}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-4gGjs8xEUbYTpbK9CzBZjKVGsSNlyXohMx7U7D2ItZA}
        - NEXT_PUBLIC_SURREALDB_CONNECTION=ws://surrealdb:8000
        - NEXT_PUBLIC_SURREALDB_USERNAME=rgtg_admin
        - NEXT_PUBLIC_SURREALDB_PASSWORD=bWFubnk6c0FzMyp6MnAh
        - NEXT_PUBLIC_SURREALDB_DB=rgtg
        - NEXT_PUBLIC_SURREALDB_NS=rgtg
        - ENGINE_URL=https://thirdwebengine:3005
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN=rightstudio.media
        - NEXT_PUBLIC_THIRDWEB_ADMIN_KEY=1361831375a445ec8e6d856ae0af0ef9fe4fe2a6c644629f62b9b70575b9814e
        - BACKEND_WALLET_ADDRESS=0x0E3e2469CaC34FC26726ee31C7E812aB739c75F8
        - ENGINE_SECRET_KEY=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIweDk3NTNGQmRBNUQzMjAxMDczMjdmZDNGNjAwMzQxOWQ3MDc1NTNhNEEiLCJzdWIiOiIweDNkMjZCNmUyMjQ1ODU5NjY2YTAwNTkxOEViQzc2OGY4ZmU1OTU0YzQiLCJhdWQiOiJ0aGlyZHdlYi5jb20iLCJleHAiOjQ5MDM0NDkxNjQsIm5iZiI6MTc0OTg0OTE2NCwiaWF0IjoxNzQ5ODQ5MTY0LCJqdGkiOiI2ZmZiNTBjOC02YTNjLTQyODItYjgxNy0zYmUxNzJiNDI3YzAiLCJjdHgiOnsicGVybWlzc2lvbnMiOiJBRE1JTiJ9fQ.MHg1ZWMxNmJlOWM2NjJiYmUxNWFhMjEwOThmNDNhN2U3ZjY0YjlkYmZiZjg5MTgwMGRkN2YwNzE4ZTcyMWM4ODI1M2U1MTdiYWFhZTY0NTEyZmI5ZjQxYjRhZGJlNjU3YjJmMzk0MDUzMzRlMTk3ZTA3NTBhNTdlNjFkZjE2Y2RlNzFj
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://app.rightstudio.media}
      - NEXT_PUBLIC_DOCS_URL=${NEXT_PUBLIC_DOCS_URL:-https://docs.rightstudio.media}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://app.rightstudio.media/api/auth}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-4gGjs8xEUbYTpbK9CzBZjKVGsSNlyXohMx7U7D2ItZA}
      - NEXT_PUBLIC_SURREALDB_CONNECTION=ws://surrealdb:8000
      - NEXT_PUBLIC_SURREALDB_USERNAME=rgtg_admin
      - NEXT_PUBLIC_SURREALDB_PASSWORD=bWFubnk6c0FzMyp6MnAh
      - NEXT_PUBLIC_SURREALDB_DB=rgtg
      - NEXT_PUBLIC_SURREALDB_NS=rgtg
      - ENGINE_URL=https://thirdwebengine:3005
      - SKIP_EXTERNAL_CONNECTIONS=false
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - BACKEND_WALLET_ADDRESS=0x0E3e2469CaC34FC26726ee31C7E812aB739c75F8
      - ENGINE_SECRET_KEY=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIweDk3NTNGQmRBNUQzMjAxMDczMjdmZDNGNjAwMzQxOWQ3MDc1NTNhNEEiLCJzdWIiOiIweDNkMjZCNmUyMjQ1ODU5NjY2YTAwNTkxOEViQzc2OGY4ZmU1OTU0YzQiLCJhdWQiOiJ0aGlyZHdlYi5jb20iLCJleHAiOjQ5MDM0NDkxNjQsIm5iZiI6MTc0OTg0OTE2NCwiaWF0IjoxNzQ5ODQ5MTY0LCJqdGkiOiI2ZmZiNTBjOC02YTNjLTQyODItYjgxNy0zYmUxNzJiNDI3YzAiLCJjdHgiOnsicGVybWlzc2lvbnMiOiJBRE1JTiJ9fQ.MHg1ZWMxNmJlOWM2NjJiYmUxNWFhMjEwOThmNDNhN2U3ZjY0YjlkYmZiZjg5MTgwMGRkN2YwNzE4ZTcyMWM4ODI1M2U1MTdiYWFhZTY0NTEyZmI5ZjQxYjRhZGJlNjU3YjJmMzk0MDUzMzRlMTk3ZTA3NTBhNTdlNjFkZjE2Y2RlNzFj
    depends_on:
      redis:
        condition: service_healthy
      surrealdb:
        condition: service_started
    networks:
      - frontend
      - backend

volumes:
  redis_data:
  surrealdb_data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend: {}
  backend: {}
