version: '3.8'

services:
  surrealdb:
    platform: 'linux/amd64'
    image: 'surrealdb/surrealdb:latest'
    command: start --user rgtg_admin --pass bWFubnk6c0FzMyp6MnAh
    ports:
      - '8000:8000'
    user: '1000:1000'
    networks:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  thirdwebengine:
    image: thirdweb/engine:latest
    environment:
      - ENCRYPTION_PASSWORD=4gGjs8xEUbYTpbK9CzBZjKVGsSNlyXohMx7U7D2ItZA
      - THIRDWEB_API_SECRET_KEY=dh4f81lxRzLmPGi2ZIQ7n22O7YVfW270NbjN6B7jnKrFnEfMB-WzJke5HQBJ_33Ke0VWaEePzajHJG-RKp2FHA
      - ADMIN_WALLET_ADDRESS=0x3d26B6e2245859666a005918EbC768f8fe5954c4
      - POSTGRES_CONNECTION_URL=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_HTTPS=true
      - CORS_ORIGINS=http://localhost:3000,https://app.rightstudio.media,https://thirdweb.com
      - ALLOWED_ORIGINS=http://localhost:3000,https://app.rightstudio.media,https://thirdweb.com
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '3005:3005'
    networks:
      - frontend
      - backend
    restart: unless-stopped

  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://app.rightstudio.media}
        - NEXT_PUBLIC_DOCS_URL=${NEXT_PUBLIC_DOCS_URL:-https://docs.rightstudio.media}
        - NEXTAUTH_URL=${NEXTAUTH_URL:-https://app.rightstudio.media/api/auth}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-4gGjs8xEUbYTpbK9CzBZjKVGsSNlyXohMx7U7D2ItZA}
        - NEXT_PUBLIC_SURREALDB_CONNECTION=http://surrealdb:8000/rpc
        - NEXT_PUBLIC_SURREALDB_USERNAME=rgtg_admin
        - NEXT_PUBLIC_SURREALDB_PASSWORD=bWFubnk6c0FzMyp6MnAh
        - NEXT_PUBLIC_SURREALDB_DB=rgtg
        - NEXT_PUBLIC_SURREALDB_NS=rgtg
        - ENGINE_URL=https://thirdwebengine:3005
        - ENGINE_SECRET_KEY=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIweDJjMzFkYkMyMjA1NjE5M0MzM2ZlMGQ2NzAzQzQ1MDgzNTZiNTE5MDciLCJzdWIiOiIweDNkMjZCNmUyMjQ1ODU5NjY2YTAwNTkxOEViQzc2OGY4ZmU1OTU0YzQiLCJhdWQiOiJ0aGlyZHdlYi5jb20iLCJleHAiOjQ5MDMxMTc4NTEsIm5iZiI6MTc0OTUxNzg1MSwiaWF0IjoxNzQ5NTE3ODUxLCJqdGkiOiI5Y2JlNTdmYi04YWI2LTQ0OTItOTQ2ZS0xZDYxZDZkZDEzZjEiLCJjdHgiOnsicGVybWlzc2lvbnMiOiJBRE1JTiJ9fQ.MHhjMDJiZTQ3MzNlYzIyYjE3NjY3Y2FlM2ExMTQwODMwNzE3NzlhOGRlNmExZjBmOTIxMGFkNzhhMzgwNTQyM2RkNzlhMTliMDdhOGY1N2NiMDBiNTk5YTJhNTA0NjcxOWRiNGNiOTRiYjA0MDAyOWEzYTcyOWU2OTI1Y2ExNTA0ZDFj
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN=rightstudio.media
        - NEXT_PUBLIC_THIRDWEB_ADMIN_KEY=1361831375a445ec8e6d856ae0af0ef9fe4fe2a6c644629f62b9b70575b9814e
        - NODE_TLS_REJECT_UNAUTHORIZED=0
        - BACKEND_WALLET_ADDRESS=0xD26EF1460F9124e3D84E38a23400dcddf9101409
        - NEXT_PUBLIC_THIRDWEB_CLIENT_ID=65ac6212af6d30a76f070edd0607b812
        - NEXT_PUBLIC_THIRDWEB_SECRET_KEY=dh4f81lxRzLmPGi2ZIQ7n22O7YVfW270NbjN6Bdh4f81lxRzLmPGi2ZIQ7n22O7YVfW270NbjN6B7jnKrFnEfMB-WzJke5HQBJ_33Ke0VWaEePzajHJG-RKp2FHA
        - RAGZ_TOKEN_ADDRESS=0xF289001ec5f52c64FA848e00bEe47CE1abbC71Aa
        - TAGZ_TOKEN_ADDRESS=0xC4Dd04fEa86A815c2195f861a4746Cb158A55db8
        - CHAIN_ID=11155111
        - MEDIA_CONTRACT_ADDRESS=0x8502a9CE80FEF99b3FCe4d9135661D5fE3bF30D5
        - NEXT_PUBLIC_MEDIA_CONTRACT_ADDRESS="0x8502a9CE80FEF99b3FCe4d9135661D5fE3bF30D5"
    image: mannyj37/rs-backend:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://app.rightstudio.media}
      - NEXT_PUBLIC_DOCS_URL=${NEXT_PUBLIC_DOCS_URL:-https://docs.rightstudio.media}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://app.rightstudio.media/api/auth}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-4gGjs8xEUbYTpbK9CzBZjKVGsSNlyXohMx7U7D2ItZA}
      - NEXT_PUBLIC_SURREALDB_CONNECTION=http://surrealdb:8000/rpc
      - NEXT_PUBLIC_SURREALDB_USERNAME=rgtg_admin
      - NEXT_PUBLIC_SURREALDB_PASSWORD=bWFubnk6c0FzMyp6MnAh
      - NEXT_PUBLIC_SURREALDB_DB=rgtg
      - NEXT_PUBLIC_SURREALDB_NS=rgtg
      - ENGINE_URL=https://thirdwebengine:3005
      - ENGINE_SECRET_KEY=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIweDJjMzFkYkMyMjA1NjE5M0MzM2ZlMGQ2NzAzQzQ1MDgzNTZiNTE5MDciLCJzdWIiOiIweDNkMjZCNmUyMjQ1ODU5NjY2YTAwNTkxOEViQzc2OGY4ZmU1OTU0YzQiLCJhdWQiOiJ0aGlyZHdlYi5jb20iLCJleHAiOjQ5MDMxMTc4NTEsIm5iZiI6MTc0OTUxNzg1MSwiaWF0IjoxNzQ5NTE3ODUxLCJqdGkiOiI5Y2JlNTdmYi04YWI2LTQ0OTItOTQ2ZS0xZDYxZDZkZDEzZjEiLCJjdHgiOnsicGVybWlzc2lvbnMiOiJBRE1JTiJ9fQ.MHhjMDJiZTQ3MzNlYzIyYjE3NjY3Y2FlM2ExMTQwODMwNzE3NzlhOGRlNmExZjBmOTIxMGFkNzhhMzgwNTQyM2RkNzlhMTliMDdhOGY1N2NiMDBiNTk5YTJhNTA0NjcxOWRiNGNiOTRiYjA0MDAyOWEzYTcyOWU2OTI1Y2ExNTA0ZDFj
      - SKIP_EXTERNAL_CONNECTIONS=false
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - BACKEND_WALLET_ADDRESS=0xD26EF1460F9124e3D84E38a23400dcddf9101409
      - NEXT_PUBLIC_THIRDWEB_CLIENT_ID=65ac6212af6d30a76f070edd0607b812
      - NEXT_PUBLIC_THIRDWEB_SECRET_KEY=dh4f81lxRzLmPGi2ZIQ7n22O7YVfW270NbjN6B
      - CHAIN_ID=11155111
      - RAGZ_TOKEN_ADDRESS=0xF289001ec5f52c64FA848e00bEe47CE1abbC71Aa
      - TAGZ_TOKEN_ADDRESS=0xC4Dd04fEa86A815c2195f861a4746Cb158A55db8
      - NEXT_PUBLIC_MEDIA_CONTRACT_ADDRESS="0x8502a9CE80FEF99b3FCe4d9135661D5fE3bF30D5"
      - MEDIA_CONTRACT_ADDRESS="0x8502a9CE80FEF99b3FCe4d9135661D5fE3bF30D5"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      thirdwebengine:
        condition: service_started
      surrealdb:
        condition: service_started
    networks:
      - frontend
      - backend

volumes:
  surrealdb_data:
  postgres_data:
  redis_data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  frontend: {}
  backend: {}
