services:
  surrealdb:
    platform: 'linux/amd64'
    image: 'surrealdb/surrealdb:latest'
    command: start --user rgtg_admin --pass bWFubnk6c0FzMyp6MnAh
    ports:
      - '8000:8000'
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    networks:
      - app-network

  next-app:
    container_name: next-app
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: mannyj37/rightstudio:dev

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

  # Add more containers below (nginx, postgres, etc.)

# Define a single network for all services to communicate
networks:
  app-network: {}
