name: mannyj37/rightstudio
services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - surrealdb
      - redis

  surrealdb:
    platform: 'linux/amd64'
    environment:
      - ragtag-demo
      - start
    image: 'surrealdb/surrealdb:latest'
    command: start --user rgtg_admin --pass bWFubnk6c0FzMyp6MnAh
    ports:
      - '8000:8000'
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network: {}
