name: mannyj37/rightstudio
services:
  surrealdb:
    platform: 'linux/amd64'
    environment:
      - ragtag-demo
      - start
    image: 'surrealdb/surrealdb:latest'
    command: start --user rgtg_admin --pass bWFubnk6c0FzMyp6MnAh
    ports:
      - '8000:8000'
    networks:
      - frontend
      - backend
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    networks:
      - frontend
      - backend
  redis:
    image: redis:7.2.4
    ports:
      - '6379:6379'
    networks:
      - frontend
      - backend
  thirdwebengine:
    build:
      context: ./thirdwebengine
      dockerfile: Dockerfile
    image: mannyj37/twengine:latest
    depends_on:
      - postgres
      - redis
    ports:
      - '3005:3005'
    networks:
      - frontend
      - backend

networks:
  # The presence of these objects is sufficient to define them
  frontend: {}
  backend: {}
