// Next Imports
import { Inter } from 'next/font/google'

// Third-party Imports
import classnames from 'classnames'
import 'react-perfect-scrollbar/dist/css/styles.css'

// Type Imports
import type { ChildrenType } from '../@core/types'

// Component Imports
import I18n from '../components/i18n'

// Style Imports
//! Do not remove the `utils.css` import below otherwise it will break the template styling
import '../@core/styles/utils.css' // Common Utility Classes
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang='en' className='d-flex width-100 min-height-100'>
      <body className={classnames(inter.className, 'd-flex width-100 min-height-100 flex-auto flex-column')}>
        <I18n />
        {children}
      </body>
    </html>
  )
}
