// Next Imports
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

// Third-party Imports
import classnames from 'classnames'
import 'react-perfect-scrollbar/dist/css/styles.css'

// Type Imports
import type { ChildrenType } from '../@core/types'

// Component Imports
import I18n from '../configs/i18n'

// Data Imports
import { langDirection } from '../data/translation/langDirection'

// Style Imports
//! Do not remove the `utils.css` import below otherwise it will break the template styling
import '../@core/styles/utils.css' // Common Utility Classes
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: ChildrenType) {
  const lang = cookies().get('lang')
  const direction = langDirection[lang?.value || 'en']

  return (
    <html lang='en' dir={direction} className='flex is-full min-bs-full'>
      <body className={classnames(inter.className, 'flex is-full min-bs-full flex-auto flex-col')}>
        <I18n lang={lang} />
        {children}
      </body>
    </html>
  )
}
