---
version: '2.0'
services:
  surrealdb:
    image: surrealdb/surrealdb
    expose:
      - port: 8000
        as: 8000
        to:
          - global: true
    env:
      - SURREAL_USER=ragtag_admin
      - SURREAL_PASS=bWFubnk6c0FzMyp6MnAh
      - SURREAL_AUTH=true
    args:
      - start
      - --user
      - ragtag_admin
      - --pass
      - bWFubnk6c0FzMyp6MnAh

profiles:
  compute:
    surrealdb:
      resources:
        cpu:
          units: 2
        memory:
          size: 32Gi
        storage:
          - size: 50Gi
  placement:
    akash:
      pricing:
        surrealdb:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
deployment:
  surrealdb:
    akash:
      profile: surrealdb
      count: 1
