FROM thirdweb/engine:latest

# Add any custom configurations if needed
ENV ENCRYPTION_PASSWORD=4gGjs8xEUbYTpbK9CzBZjKVGsSNlyXohMx7U7D2ItZA
ENV THIRDWEB_API_SECRET_KEY="kmYo0w4r2cIg8Vkrm4_3DReCyEUbLVs7Qt-AUc6qKCfhMV_I8_KBQRlJoQHiVaruTb7eHuzxinSZfYEQHinetw"
ENV ADMIN_WALLET_ADDRESS=0x3d26B6e2245859666a005918EbC768f8fe5954c4
ENV POSTGRES_CONNECTION_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres?sslmode=disable
ENV REDIS_URL=redis://host.docker.internal:6379/0
ENV ENABLE_HTTPS=true
# ENV NODE_TLS_REJECT_UNAUTHORIZED=0

EXPOSE 3005
